/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClubRouteImport } from './routes/club'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubDashboardRouteImport } from './routes/club/dashboard'
import { Route as ClubCreateRouteImport } from './routes/club/create'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ClubDashboardClub_idRouteImport } from './routes/club/dashboard/$club_id'
import { Route as ClubDashboardClub_idIndexRouteImport } from './routes/club/dashboard/$club_id/index'

const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubDashboardRoute = ClubDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClubRoute,
} as any)
const ClubCreateRoute = ClubCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ClubRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ClubDashboardClub_idRoute = ClubDashboardClub_idRouteImport.update({
  id: '/$club_id',
  path: '/$club_id',
  getParentRoute: () => ClubDashboardRoute,
} as any)
const ClubDashboardClub_idIndexRoute =
  ClubDashboardClub_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClubDashboardClub_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/club/create': typeof ClubCreateRoute
  '/club/dashboard': typeof ClubDashboardRouteWithChildren
  '/club/dashboard/$club_id': typeof ClubDashboardClub_idRouteWithChildren
  '/club/dashboard/$club_id/': typeof ClubDashboardClub_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/club/create': typeof ClubCreateRoute
  '/club/dashboard': typeof ClubDashboardRouteWithChildren
  '/club/dashboard/$club_id': typeof ClubDashboardClub_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/club': typeof ClubRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/club/create': typeof ClubCreateRoute
  '/club/dashboard': typeof ClubDashboardRouteWithChildren
  '/club/dashboard/$club_id': typeof ClubDashboardClub_idRouteWithChildren
  '/club/dashboard/$club_id/': typeof ClubDashboardClub_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/club/create'
    | '/club/dashboard'
    | '/club/dashboard/$club_id'
    | '/club/dashboard/$club_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/club/create'
    | '/club/dashboard'
    | '/club/dashboard/$club_id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/club'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/dashboard'
    | '/club/create'
    | '/club/dashboard'
    | '/club/dashboard/$club_id'
    | '/club/dashboard/$club_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ClubRoute: typeof ClubRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/dashboard': {
      id: '/club/dashboard'
      path: '/dashboard'
      fullPath: '/club/dashboard'
      preLoaderRoute: typeof ClubDashboardRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/create': {
      id: '/club/create'
      path: '/create'
      fullPath: '/club/create'
      preLoaderRoute: typeof ClubCreateRouteImport
      parentRoute: typeof ClubRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/club/dashboard/$club_id': {
      id: '/club/dashboard/$club_id'
      path: '/$club_id'
      fullPath: '/club/dashboard/$club_id'
      preLoaderRoute: typeof ClubDashboardClub_idRouteImport
      parentRoute: typeof ClubDashboardRoute
    }
    '/club/dashboard/$club_id/': {
      id: '/club/dashboard/$club_id/'
      path: '/'
      fullPath: '/club/dashboard/$club_id/'
      preLoaderRoute: typeof ClubDashboardClub_idIndexRouteImport
      parentRoute: typeof ClubDashboardClub_idRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ClubDashboardClub_idRouteChildren {
  ClubDashboardClub_idIndexRoute: typeof ClubDashboardClub_idIndexRoute
}

const ClubDashboardClub_idRouteChildren: ClubDashboardClub_idRouteChildren = {
  ClubDashboardClub_idIndexRoute: ClubDashboardClub_idIndexRoute,
}

const ClubDashboardClub_idRouteWithChildren =
  ClubDashboardClub_idRoute._addFileChildren(ClubDashboardClub_idRouteChildren)

interface ClubDashboardRouteChildren {
  ClubDashboardClub_idRoute: typeof ClubDashboardClub_idRouteWithChildren
}

const ClubDashboardRouteChildren: ClubDashboardRouteChildren = {
  ClubDashboardClub_idRoute: ClubDashboardClub_idRouteWithChildren,
}

const ClubDashboardRouteWithChildren = ClubDashboardRoute._addFileChildren(
  ClubDashboardRouteChildren,
)

interface ClubRouteChildren {
  ClubCreateRoute: typeof ClubCreateRoute
  ClubDashboardRoute: typeof ClubDashboardRouteWithChildren
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubCreateRoute: ClubCreateRoute,
  ClubDashboardRoute: ClubDashboardRouteWithChildren,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ClubRoute: ClubRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
